import Head from "next/head";
import HomeScreen from "../screens/Home";
// import path from "path";
// import fs from "fs";
import Footer from "../components/layout/Footer";

export default function Home(first_slideshow) {
  // const data = { ...first_slideshow };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeScreen  />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

// export async function getStaticProps() {
//   const FSSlidePath = path.join(process.cwd(), "data", "first_slideshow.json");
//   const FSSlideContent = fs.readFileSync(FSSlidePath, "utf8");
//   const first_slideshow = JSON.parse(FSSlideContent);

//   return {
//     props: {
//       first_slideshow,
//     },
//   };
// }
